// File generated by Claude

// DijkstraPathfinding.js
export class DijkstraPathfinding {
    constructor(scene, grid) {
        this.scene = scene;
        this.grid = grid; // 2D array: 0 = walkable, 1 = wall
        this.tileSize = 32;
    }

    worldToGrid(x, y) {
        return {
            col: Math.floor(x / this.tileSize),
            row: Math.floor(y / this.tileSize)
        };
    }

    gridToWorld(col, row) {
        return {
            x: col * this.tileSize + this.tileSize / 2,
            y: row * this.tileSize + this.tileSize / 2
        };
    }

    getNeighbors(col, row) {
        const dirs = [
            { dc: 1, dr: 0 }, { dc: -1, dr: 0 },  // left, right
            { dc: 0, dr: 1 }, { dc: 0, dr: -1 },  // up, down
            { dc: 1, dr: -1 }, { dc: -1, dr: -1 } // jump-style diagonals
        ];
        const neighbors = [];
        for (const { dc, dr } of dirs) {
            const nc = col + dc, nr = row + dr;
            if (
                nr >= 0 && nr < this.grid.length &&
                nc >= 0 && nc < this.grid[0].length &&
                this.grid[nr][nc] === 0
            ) {
                neighbors.push({ col: nc, row: nr });
            }
        }
        return neighbors;
    }

    findPath(startX, startY, targetX, targetY) {
        const start = this.worldToGrid(startX, startY);
        const target = this.worldToGrid(targetX, targetY);

        const key = (c, r) => `${c},${r}`;
        const dist = {};
        const prev = {};
        const visited = new Set();
        const queue = [{ col: start.col, row: start.row, cost: 0 }];

        dist[key(start.col, start.row)] = 0;

        while (queue.length > 0) {
            // Pop lowest cost node
            queue.sort((a, b) => a.cost - b.cost);
            const { col, row, cost } = queue.shift();
            const k = key(col, row);

            if (visited.has(k)) continue;
            visited.add(k);

            if (col === target.col && row === target.row) break;

            for (const neighbor of this.getNeighbors(col, row)) {
                const nk = key(neighbor.col, neighbor.row);
                const newCost = cost + 1;
                if (dist[nk] === undefined || newCost < dist[nk]) {
                    dist[nk] = newCost;
                    prev[nk] = { col, row };
                    queue.push({ ...neighbor, cost: newCost });
                }
            }
        }

        // Reconstruct path
        const path = [];
        let cur = target;
        while (cur && !(cur.col === start.col && cur.row === start.row)) {
            path.unshift(this.gridToWorld(cur.col, cur.row));
            const p = prev[key(cur.col, cur.row)];
            if (!p) return []; // No path found
            cur = p;
        }

        return path;
    }
}