
export class EnemyIdleState extends State {

    enter(scene, enemy) {
        console.log('Entered Idle State');
        enemy.setVelocityX(0);

        //enemy.play('Idle);
    }

    execute(scene, enemy) {
        const dist = Phaser.Math.Distance.Between(
            enemy.x, enemy.y, scene.player.x, scene.player.y
        );

        if (dist < screen.width) {
            enemy.StateMachine.transition('chase');
        }
    }
}

export class EnemyChaseState extends State {
    enter(scene, enemy) {
        enemy.CurrentPath = [];
        enemy.pathtimer = 0;
        enemy.play('Walk');
        console.log('Entered Chase State');
    }
    
    execute(scene, enemy) {
        const dist = Phaser.Math.Distance.Between(
            enemy.x, enemy.y, scene.player.x, scene.player.y

        );
        if (dist > screen.width) {
            enemy.StateMachine.transition('idle');
        }
        // generated by Claude and adapted by me
        if (enemy.pathtimer <= 0) {
            const path = scene.dijkstra.findPath(enemy.x, enemy.y, scene.player.x, scene.player.y);
            enemy.CurrentPath = path;
            enemy.pathtimer = 30; // Recalculate path every 30 frames
        } else {
            enemy.pathtimer--;
        }

        if (enemy.CurrentPath.length > 0) {
            const nextPoint = enemy.CurrentPath[0];
            const angle = Phaser.Math.Angle.Between(enemy.x, enemy.y, nextPoint.x, nextPoint.y);
            const speed = 2;
            enemy.setVelocity(Math.cos(angle) * speed, Math.sin(angle) * speed);

            if (Phaser.Math.Distance.Between(enemy.x, enemy.y, nextPoint.x, nextPoint.y) < 4) {
                enemy.CurrentPath.shift(); // Move to next point in path
            }
        } else {
            enemy.setVelocity(0);
        }
        
    }
}
